server:
  port: 8082
spring:
  application:
    name: VOITURE-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3333/carservicedb?createDatabaseIfNotExist=true
    username: "root"
    password: ""

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true